function [uniform] = LGM(iterations, seed)
  m = 2^31 - 1;
  a = 7^5;
  b = 0;
  xj = seed;
  %Ui is uniformly distributed random number.
  ui = 0.0;
  
  for i = 1:iterations
		%Define Xi
		xi = (a*xj + b);
		xi = mod(xi, m);%xi % m;
		ui = xi / m;
		%See above
		xj = xi;	
		%Insert the uniformly distributed random number generated by LGM into the array
		uniform(i) = ui;
  end;
end
